import { _decorator, Component, Node } from 'cc';
import { Element, TypeSkill } from '../Model/PetDTO';
const { ccclass, property } = _decorator;
export interface SkillDataInfor {
    idSkill: string;
    name: string;
    type: Element;
    typeSkill: TypeSkill;
    attack: number;
    accuracy: number;
    powerPoints: number;
    description: string;
}

export const SkillList: SkillDataInfor[] = [
    {
        idSkill: "ATTACK01",
        name: "Đánh Thường",
        type: Element.Normal,
        typeSkill: TypeSkill.ATTACK,
        attack: 20,
        accuracy: 100,
        powerPoints: 30,
        description: "Pet tấn công vào đối thủ và gây sát thương",
    },
    {
        idSkill: "NOR01",
        name: "Gầm Gừ",
        type: Element.Normal,
        typeSkill: TypeSkill.INCREASE_ATTACK,
        attack: 0,
        accuracy: 100,
        powerPoints: 15,
        description: "Growl khiến đối thủ sợ hãi, từ đó giảm 5 chỉ số Attack của đối thủ",
    },
    {
        idSkill: "NOR02",
        name: "Bảo Vệ",
        type: Element.Normal,
        typeSkill: TypeSkill.DEFENSE,
        attack: 0,
        accuracy: 100,
        powerPoints: 10,
        description: "Tạo 1 lớp khiên bảo vệ, miễn đòn tấn công của đối thủ",
    },
    {
        idSkill: "NOR03",
        name: "Nghỉ Ngơi",
        type: Element.Normal,
        typeSkill: TypeSkill.HEAL,
        attack: 0,
        accuracy: 100,
        powerPoints: 10,
        description: "Pet rơi vào trạng thái ngủ trong 2 lượt (Không thể dùng skill trong lúc ngủ), Hồi đầy thanh máu",
    },
    {
        idSkill: "NOR04",
        name: "Rối Loạn Tâm Trí",
        type: Element.Normal,
        typeSkill: TypeSkill.DECREASE_ATTACK,
        attack: 10,
        accuracy: 100,
        powerPoints: 10,
        description: "Pet Tấn công đối thủ làm giảm chỉ số tấn công đối thủ đi 50% cho lượt tiếp theo",
    },
    {
        idSkill: "NOR05",
        name: "Cắt",
        type: Element.Normal,
        typeSkill: TypeSkill.ATTACK,
        attack: 0,
        accuracy: 50,
        powerPoints: 95,
        description: "Pet  nhát chém lên đối thủ ",
    },
    {
        idSkill: "NOR06",
        name: "Đánh Thẳng",
        type: Element.Normal,
        typeSkill: TypeSkill.ATTACK,
        attack: 35,
        accuracy: 100,
        powerPoints: 95,
        description: "Pet dùng sức mạnh đấm đối thủ ",
    },
    {
        idSkill: "NOR07",
        name: "Song Cước",
        type: Element.Normal,
        typeSkill: TypeSkill.ATTACK,
        attack: 30,
        accuracy: 100,
        powerPoints: 95,
        description: "Pet sẽ Tấn công 2 lần liên tiếp trong 1 lượt",
    },
    {
        idSkill: "NOR08",
        name: "Cắn",
        type: Element.Normal,
        typeSkill: TypeSkill.ATTACK,
        attack: 60,
        accuracy: 100,
        powerPoints: 95,
        description: "Pet sử dụng hàm răng sắt nhọn để cắn đối thủ",
    },
    {
        idSkill: "NOR09",
        name: "Vuốt Nghiền",
        type: Element.Normal,
        typeSkill: TypeSkill.ATTACK,
        attack: 75,
        accuracy: 95,
        powerPoints: 95,
        description: "Pet dùng móng vuốt cào đối thủ",
    },
    {
        idSkill: "NOR10",
        name: "Cánh Tấn Công",
        type: Element.Normal,
        typeSkill: TypeSkill.ATTACK,
        attack: 60,
        accuracy: 100,
        powerPoints: 95,
        description: "Pet dùng đôi cánh lớn tạo cơn lốc tấn công đối thủ",
    },
    {
        idSkill: "NOR11",
        name: "Bay",
        type: Element.Normal,
        typeSkill: TypeSkill.ATTACK,
        attack: 75,
        accuracy: 95,
        powerPoints: 95,
        description: "Pet sẽ bay lên vào lao tới tấn công đối thủ",
    },
    {
        idSkill: "NOR12",
        name: "Cú đấm liên hoàn",
        type: Element.Normal,
        typeSkill: TypeSkill.ATTACK,
        attack: -1,
        accuracy: 30,
        powerPoints: 95,
        description: "Khi dùng chiêu Pet sẽ tập trung sức mạnh và đấm liên tục vào đối thủ. Nếu đánh trúng sẽ kết liễu đối thủ còn nếu hụt sẽ làm bản thân bị thương mất 50% máu (Có thể bị chặn bởi protect)",
    },
    {
        idSkill: "NOR13",
        name: "Động Đất",
        typeSkill: TypeSkill.ATTACK,
        type: Element.Normal,
        attack: 100,
        accuracy: 100,
        powerPoints: 95,
        description: "Pet sẽ tạo ra địa chấn làm gây dame lên đối thủ",
    },
    {
        idSkill: "GRASS01",
        name: "Phi Dao Lá",
        type: Element.Grass,
        typeSkill: TypeSkill.ATTACK,
        attack: 50,
        accuracy: 100,
        powerPoints: 10,
        description: "Pet ném những chiếc lá sắc bén về đối thủ",
    },
    {
        idSkill: "GRASS02",
        name: "Hấp Thụ",
        type: Element.Grass,
        typeSkill: TypeSkill.ATTACK,
        attack: 0,
        accuracy: 100,
        powerPoints: 10,
        description: "Pet dùng khả năng của hồi phục cho bản thân với 50% lượng máu tối đa",
    },
    {
        idSkill: "ELECTRIC01",
        name: "Tia Sét",
        type: Element.Electric,
        typeSkill: TypeSkill.ATTACK,
        attack: 110,
        accuracy: 100,
        powerPoints: 10,
        description: "Pet gọi sét phòng xuống mục tiêu và gây sát thương",
    },
    {
        idSkill: "ELECTRIC02",
        name: "Sóng Điện",
        type: Element.Electric,
        typeSkill: TypeSkill.ATTACK,
        attack: 90,
        accuracy: 70,
        powerPoints: 10,
        description: "Pet gọi phóng ra 1 luồng điện vào đối thủ và gấy sát thương",
    },
    {
        idSkill: "ELECTRIC03",
        name: "Quả cầu điện",
        type: Element.Electric,
        typeSkill: TypeSkill.ATTACK,
        attack: 100,
        accuracy: 100,
        powerPoints: 10,
        description: "Pet tạo ra 1 quả cầu điện với năng lượng cực mạnh tấn công vào đối thủ",
    },
    {
        idSkill: "WATER01",
        name: "Quăng bóng nước",
        type: Element.Water,
        typeSkill: TypeSkill.ATTACK,
        attack: 40,
        accuracy: 100,
        powerPoints: 10,
        description: "Pet quăng bóng nước và gây sát thương",
    },
    {
        idSkill: "WATER02",
        name: "Thả bóng nước",
        type: Element.Water,
        typeSkill: TypeSkill.ATTACK,
        attack: 60,
        accuracy: 100,
        powerPoints: 10,
        description: "Pet tạo bong bóng nước thả xuống đối phương",
    },
    {
        idSkill: "WATER03",
        name: "Chém Nước",
        type: Element.Water,
        typeSkill: TypeSkill.ATTACK,
        attack: 110,
        accuracy: 100,
        powerPoints: 10,
        description: "Pet tạo những chém nước vào đối thủ vào gây sát thương",
    },
    {
        idSkill: "FIRE01",
        name: "Tia Lửa",
        type: Element.Fire,
        typeSkill: TypeSkill.ATTACK,
        attack: 40,
        accuracy: 100,
        powerPoints: 10,
        description: "Pet phun 1 ngọn lửa nhỏ vào đối thủ và gây sát thương",
    },
    {
        idSkill: "FIRE02",
        name: "Đại Hỏa Bạo",
        type: Element.Fire,
        typeSkill: TypeSkill.ATTACK,
        attack: 120,
        accuracy: 100,
        powerPoints: 10,
        description: "Pet phun một ngọn lửa hình chữ thập vào đối thủ và gây sát thương",
    },
    {
        idSkill: "FIRE03",
        name: "Nhiệt Hủy Diệt",
        type: Element.Fire,
        typeSkill: TypeSkill.ATTACK,
        attack: 90,
        accuracy: 100,
        powerPoints: 10,
        description: "Pet phun lượng lửa cực nóng vào đối thủ và gây sát thương",
    },
    {
        idSkill: "ICE01",
        name: "Cầu Băng",
        type: Element.Ice,
        typeSkill: TypeSkill.ATTACK,
        attack: 30,
        accuracy: 70,
        powerPoints: 10,
        description: "Pet sẽ quăng ball vào đối thủ trong 4 lượt tiếp theo, Nếu không trượt dame sẽ tăng gấp đôi mỗi lượt (30 → 60 → 120 → 240)",
    },
    {
        idSkill: "ICE02",
        name: "Băng Rơi",
        type: Element.Ice,
        typeSkill: TypeSkill.ATTACK,
        attack: 90,
        accuracy: 100,
        powerPoints: 10,
        description: "Pet triệu hồi những mảnh băng và gây sát thương",
    },
    {
        idSkill: "ICE03",
        name: "Nanh băng",
        type: Element.Ice,
        typeSkill: TypeSkill.ATTACK,
        attack: 90,
        accuracy: 100,
        powerPoints: 10,
        description: "Pet dùng răng nanh băng giá của mình tấn công đối thủ. Nếu trong môi trường băng giá sẽ x2 sát thương",
    },
    {
        idSkill: "DRAGON01",
        name: "Vuốt Rồng",
        type: Element.Dragon,
        typeSkill: TypeSkill.ATTACK,
        attack: 100,
        accuracy: 100,
        powerPoints: 10,
        description: "Pet dùng móng vuốt của rồng để tấn công đối thủ, có 50% giảm 10 phòng thủ của đối thủ",
    },
];
