import { _decorator, Component, Node } from 'cc';
import { AnimalElement } from '../Model/PetDTO';
const { ccclass, property } = _decorator;
export interface SkillDataInfor {
    idSkill: string;
    name: string;
    type: AnimalElement;
    attack: number;
    accuracy: number;
    powerPoints: number;
    description: string;
}

export const SkillList: SkillDataInfor[] = [
    {
        idSkill: "ATTACK01",
        name: "Đánh Thường",
        type: AnimalElement.Normal,
        attack: 20,
        accuracy: 100,
        powerPoints: 30,
        description: "Pet tấn công vào đối thủ và gây sát thương",
    },
    {
        idSkill: "NOR01",
        name: "Growl - Gầm Gừ",
        type: AnimalElement.Normal,
        attack: 0,
        accuracy: 100,
        powerPoints: 15,
        description: "Growl khiến đối thủ sợ hãi, từ đó giảm 5 chỉ số Attack của đối thủ",
    },
    {
        idSkill: "NOR02",
        name: "Protect - Bảo Vệ",
        type: AnimalElement.Normal,
        attack: 0,
        accuracy: 100,
        powerPoints: 10,
        description: "Tạo 1 lớp khiên bảo vệ, miễn đòn tấn công của đối thủ",
    },
    {
        idSkill: "NOR03",
        name: "Rest - Nghỉ Ngơi",
        type: AnimalElement.Normal,
        attack: 0,
        accuracy: 100,
        powerPoints: 10,
        description: "Pet rơi vào trạng thái ngủ trong 2 lượt (Không thể dùng skill trong lúc ngủ), Hồi đầy thanh máu",
    },
    {
        idSkill: "NOR04",
        name: "Confusion - Rối Loạn Tâm Trí",
        type: AnimalElement.Normal,
        attack: 10,
        accuracy: 100,
        powerPoints: 10,
        description: "Pet Tấn công đối thủ làm giảm chỉ số tấn công đối thủ đi 50% cho lượt tiếp theo",
    },
    {
        idSkill: "NOR05",
        name: "Cut - Cắt",
        type: AnimalElement.Normal,
        attack: 0,
        accuracy: 50,
        powerPoints: 95,
        description: "Pet  nhát chém lên đối thủ ",
    },
    {
        idSkill: "NOR06",
        name: "Pound - Đánh Thẳng",
        type: AnimalElement.Normal,
        attack: 35,
        accuracy: 100,
        powerPoints: 95,
        description: "Pet dùng sức mạnh đấm đối thủ ",
    },
    {
        idSkill: "NOR07",
        name: "Double Kick - Song Cước",
        type: AnimalElement.Normal,
        attack: 30,
        accuracy: 100,
        powerPoints: 95,
        description: "Pet sẽ Tấn công 2 lần liên tiếp trong 1 lượt",
    },
    {
        idSkill: "NOR08",
        name: "Bite - Cắn",
        type: AnimalElement.Normal,
        attack: 60,
        accuracy: 100,
        powerPoints: 95,
        description: "Pet sử dụng hàm răng sắt nhọn để cắn đối thủ",
    },
    {
        idSkill: "NOR09",
        name: "Crush Claw - Vuốt Nghiền",
        type: AnimalElement.Normal,
        attack: 75,
        accuracy: 95,
        powerPoints: 95,
        description: "Pet dùng móng vuốt cào đối thủ",
    },
    {
        idSkill: "NOR10",
        name: "Wing Attack – Cánh Tấn Công",
        type: AnimalElement.Normal,
        attack: 60,
        accuracy: 100,
        powerPoints: 95,
        description: "Pet dùng đôi cánh lớn tạo cơn lốc tấn công đối thủ",
    },
    {
        idSkill: "NOR11",
        name: "Fly - Bay",
        type: AnimalElement.Normal,
        attack: 75,
        accuracy: 95,
        powerPoints: 95,
        description: "Pet sẽ bay lên vào lao tới tấn công đối thủ",
    },
    {
        idSkill: "NOR12",
        name: "Fury Punch - Cú đấm liên hoàn",
        type: AnimalElement.Normal,
        attack: -1,
        accuracy: 30,
        powerPoints: 95,
        description: "Khi dùng chiêu Pet sẽ tập trung sức mạnh và đấm liên tục vào đối thủ. Nếu đánh trúng sẽ kết liễu đối thủ còn nếu hụt sẽ làm bản thân bị thương mất 50% máu (Có thể bị chặn bởi protect)",
    },
    {
        idSkill: "NOR13",
        name: "Earthquake - Động Đất",
        type: AnimalElement.Normal,
        attack: 100,
        accuracy: 100,
        powerPoints: 95,
        description: "Pet sẽ tạo ra địa chấn làm gây dame lên đối thủ",
    },
    {
        idSkill: "GRASS01",
        name: "Razor Leaf - Phi Dao Lá",
        type: AnimalElement.Grass,
        attack: 50,
        accuracy: 100,
        powerPoints: 10,
        description: "Pet ném những chiếc lá sắc bén về đối thủ",
    },
    {
        idSkill: "GRASS02",
        name: "Absorb - Hấp Thụ",
        type: AnimalElement.Grass,
        attack: 0,
        accuracy: 100,
        powerPoints: 10,
        description: "Pet dùng khả năng của hồi phục cho bản thân với 50% lượng máu tối đa",
    },
    {
        idSkill: "ELECTRIC01",
        name: "Thunderbolt - Tia Sét",
        type: AnimalElement.Electric,
        attack: 110,
        accuracy: 100,
        powerPoints: 10,
        description: "Pet gọi sét phòng xuống mục tiêu và gây sát thương",
    },
    {
        idSkill: "ELECTRIC02",
        name: "Thunder Wave - Sóng Điện",
        type: AnimalElement.Electric,
        attack: 90,
        accuracy: 70,
        powerPoints: 10,
        description: "Pet gọi phóng ra 1 luồng điện vào đối thủ và gấy sát thương",
    },
    {
        idSkill: "ELECTRIC03",
        name: "Electro Ball -  Quả cầu điện",
        type: AnimalElement.Electric,
        attack: 100,
        accuracy: 100,
        powerPoints: 10,
        description: "Pet tạo ra 1 quả cầu điện với năng lượng cực mạnh tấn công vào đối thủ",
    },
    {
        idSkill: "WATER01",
        name: "Water Gun - Quăng bóng nước",
        type: AnimalElement.Water,
        attack: 40,
        accuracy: 100,
        powerPoints: 10,
        description: "Pet quăng bóng nước và gây sát thương",
    },
    {
        idSkill: "WATER02",
        name: "Bubble - Thả bóng nước",
        type: AnimalElement.Water,
        attack: 60,
        accuracy: 100,
        powerPoints: 10,
        description: "Pet tạo bong bóng nước thả xuống đối phương",
    },
    {
        idSkill: "WATER03",
        name: "Aqua Cutter - Chém Nước",
        type: AnimalElement.Water,
        attack: 110,
        accuracy: 100,
        powerPoints: 10,
        description: "Pet tạo những chém nước vào đối thủ vào gây sát thương",
    },
    {
        idSkill: "FIRE01",
        name: "Ember - Tia Lửa",
        type: AnimalElement.Fire,
        attack: 40,
        accuracy: 100,
        powerPoints: 10,
        description: "Pet phun 1 ngọn lửa nhỏ vào đối thủ và gây sát thương",
    },
    {
        idSkill: "FIRE02",
        name: "Fire Blast - Đại Hỏa Bạo",
        type: AnimalElement.Fire,
        attack: 120,
        accuracy: 100,
        powerPoints: 10,
        description: "Pet phun một ngọn lửa hình chữ thập vào đối thủ và gây sát thương",
    },
    {
        idSkill: "FIRE03",
        name: "Overheat - Nhiệt Hủy Diệt",
        type: AnimalElement.Fire,
        attack: 90,
        accuracy: 100,
        powerPoints: 10,
        description: "Pet phun lượng lửa cực nóng vào đối thủ và gây sát thương",
    },
    {
        idSkill: "ICE01",
        name: "Ice Ball - Cầu Băng",
        type: AnimalElement.Ice,
        attack: 30,
        accuracy: 70,
        powerPoints: 10,
        description: "Pet sẽ quăng ball vào đối thủ trong 4 lượt tiếp theo, Nếu không trượt dame sẽ tăng gấp đôi mỗi lượt (30 → 60 → 120 → 240)",
    },
    {
        idSkill: "ICE02",
        name: "Icicle Crash - Băng Rơi",
        type: AnimalElement.Ice,
        attack: 90,
        accuracy: 100,
        powerPoints: 10,
        description: "Pet triệu hồi những mảnh băng và gây sát thương",
    },
    {
        idSkill: "ICE03",
        name: "Ice Fang - Nanh băng",
        type: AnimalElement.Ice,
        attack: 90,
        accuracy: 100,
        powerPoints: 10,
        description: "Pet dùng răng nanh băng giá của mình tấn công đối thủ. Nếu trong môi trường băng giá sẽ x2 sát thương",
    },
    {
        idSkill: "DRAGON01",
        name: "Dragon Claw - Vuốt Rồng",
        type: AnimalElement.Dragon,
        attack: 100,
        accuracy: 100,
        powerPoints: 10,
        description: "Pet dùng móng vuốt của rồng để tấn công đối thủ, có 50% giảm 10 phòng thủ của đối thủ",
    },
];
