export enum UIID {
    None = 0,
    Home = 1,
    Shop = 2,
    Inventory = 3,
    Notice = 4,
    myProfile = 5,
    Help = 6,
    SlotMachine = 7,
    MoodList = 8,
    SendToken = 9,
    Settings = 10,
    AboutUs = 11,
    MathProblem = 12,
    GlobalChat= 13,
    NoticeBig = 14,
}