export enum UIID {
    None = 0,
    Home = 1,
    Gameplay = 2,
    Popup_Finish = 3,
    Popup_Buff = 4,
    Leader_Board = 5,
    Daily_Reward = 6,
    Friend = 7,
    Comming_Soon = 8,
    Claim_Friend_Gift = 9,
    Booster = 10,
    Purchase_Panel = 11,
    Mission = 12,
    Skin = 13,
    Airdrop = 14,
    QR_Popup = 15,
    Disclaimer_Popup = 16,
    Setting = 17,
    Shop = 18,
    Wallet = 19,
    ShopSkins = 20,
    ShopPremium = 21,
    PowerUp = 22,
    Animal = 23,
}