export enum MessageTypes {
    OPEN_DOOR = "open_door",
    ON_OPEN_DOOR = "on_open_door",
    CLOSE_DOOR = "close_door",
    ON_CLOSE_DOOR = "on_close_door",
    BATTE_ROOM_READY = "battle_room_ready",
    BATTE_READY = "battle_ready",
    PLAYER_ACION = "player_action",
    RESULT_SKILL = "result_skill",
    SWITCH_PET_AFTER_DEAD = "switch_pet_after_dead",
    SWITCH_PET_AFTER_DEAD_DONE = "switch_pet_after_dead_done",
    BATTLE_FINISHED = "battle_finished",
    WAITING_OTHER_USER = "waiting_other_user",
    SURRENDER_BATTLE = "surrender_battle",
    SET_PET_SLEEP = "set_pet_sleep",
    DISCONNECTED = "Disconnected",
    END_BATTLE = "end_battle",
    END_BATTLE_COMPLETED = " end_battle_completed",
    NOT_PET_BATTLE = "not_pet_battle",
    NOT_ENOUGH_PET_BATTLE = "not_enough_pet_battle",
    NOT_ENOUGH_SKILL_PET_BATTLE = "not_enough_skill_pet_battle",
    NOTIFY_BATTLE = "notify_battle",
}